from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import pytest

from llm_email_app.agent.graph import AgentRuntime
from llm_email_app.agent.state import InvocationContext


class FakeLLMClient:
    def __init__(
        self,
        *,
        summary: str = "Summary generated by the fake LLM.",
        proposals: Optional[List[Dict[str, Any]]] = None,
        matches: Optional[List[Dict[str, Any]]] = None,
        draft_reply: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.summary = summary
        self.proposals = proposals or []
        self.matches = matches or []
        self.draft_reply = draft_reply

    def summarize_email(self, **kwargs: Any) -> Dict[str, Any]:
        return {
            "text": self.summary,
            "proposals": list(self.proposals),
            "draft_reply": self.draft_reply,
        }

    def evaluate_label_rules(self, **kwargs: Any) -> Dict[str, Any]:
        return {
            "matches": list(self.matches),
        }


class FakeGmailClient:
    def __init__(self) -> None:
        self.service = object()
        self.messages: Dict[str, Dict[str, Any]] = {
            "email-1": {
                "id": "email-1",
                "threadId": "thread-1",
                "from": "Alice <alice@example.com>",
                "subject": "Budget review meeting",
                "body": "Can we meet next Tuesday at 10am to review the budget?",
                "snippet": "Can we meet next Tuesday at 10am",
                "received": "2026-05-05T08:00:00+00:00",
                "labels": ["INBOX"],
                "label_ids": ["INBOX"],
            },
            "demo-inbox-client-launch": {
                "id": "demo-inbox-client-launch",
                "threadId": "thread-client-launch",
                "from": "Maya Patel <maya@northstarstudios.co>",
                "subject": "Need confirmation: client launch rehearsal on 2026-05-08 at 15:00",
                "body": "Can you confirm the client launch rehearsal on 2026-05-08 at 15:00 HKT?",
                "snippet": "Can you confirm the client launch rehearsal on 2026-05-08 at 15:00 HKT?",
                "received": "2026-05-06T08:35:00+08:00",
                "labels": ["INBOX", "Action Needed"],
                "label_ids": ["INBOX", "Action Needed"],
                "event_request": {
                    "title": "Client launch rehearsal",
                    "start": "2026-05-08T15:00:00+08:00",
                    "end": "2026-05-08T15:30:00+08:00",
                    "timeZone": "Asia/Hong_Kong",
                    "location": "Zoom",
                    "notes": "30-minute rehearsal with design and ops leads.",
                    "attendees": ["maya@northstarstudios.co"],
                },
                "scenario_id": "client_launch_conflict",
                "demo_role": "flagship",
            },
            "demo-inbox-budget": {
                "id": "demo-inbox-budget",
                "threadId": "thread-budget",
                "from": "Jordan Wu <jordan.wu@acme-capital.example>",
                "subject": "Budget review follow-up and requested reply",
                "body": "Please send me a reply draft today confirming whether you can join the budget review next Tuesday at 10:00.",
                "snippet": "Please send me a reply draft today confirming whether you can join the budget review next Tuesday at 10:00.",
                "received": "2026-05-06T07:10:00+08:00",
                "labels": ["INBOX", "Finance"],
                "label_ids": ["INBOX", "Finance"],
                "scenario_id": "budget_summary",
                "demo_role": "support",
            },
        }
        self.applied_labels: List[Dict[str, Any]] = []
        self.created_drafts: List[Dict[str, Any]] = []

    def fetch_mailbox_overview(self, active_folder: str = "inbox", page: int = 1, per_page: int = 20, days: int = 7) -> Dict[str, Any]:
        items = list(self.messages.values())[:per_page]
        return {
            "active_folder": active_folder,
            "page": page,
            "per_page": per_page,
            "days": days,
            "folders": {
                active_folder: {
                    "label": active_folder.upper(),
                    "page": page,
                    "has_next_page": False,
                    "items": items,
                }
            },
        }

    def fetch_emails_since(self, days: int = 7, max_results: Optional[int] = None) -> List[Dict[str, Any]]:
        items = list(self.messages.values())
        return items[:max_results] if max_results else items

    def get_message(self, message_id: str) -> Optional[Dict[str, Any]]:
        return self.messages.get(message_id)

    def check_or_create_label(self, label_name: str) -> str:
        return f"label-{label_name.lower()}"

    def apply_labels_to_message(self, message_id: str, label_ids: List[str]) -> bool:
        self.applied_labels.append({"message_id": message_id, "label_ids": list(label_ids)})
        return True

    def create_draft(self, to: str, subject: str, body: str, reply_to_message_id: Optional[str] = None) -> Dict[str, Any]:
        draft = {
            "id": f"draft-{len(self.created_drafts) + 1}",
            "message": {"id": f"draft-message-{len(self.created_drafts) + 1}"},
            "to": to,
            "subject": subject,
            "body": body,
            "reply_to_message_id": reply_to_message_id,
        }
        self.created_drafts.append(draft)
        return draft


class FakeGCalClient:
    def __init__(self) -> None:
        self.service = object()
        self.events: List[Dict[str, Any]] = []
        self.created: List[Dict[str, Any]] = []
        self.updated: List[Dict[str, Any]] = []
        self.deleted: List[str] = []

    def list_events(self, max_results: int = 50, time_min: Optional[str] = None, time_max: Optional[str] = None) -> List[Dict[str, Any]]:
        return list(self.events)[:max_results]

    def create_event(self, proposal: Dict[str, Any]) -> str:
        self.created.append(dict(proposal))
        return f"event-{len(self.created)}"

    def update_event(self, event_id: str, updates: Dict[str, Any]) -> str:
        self.updated.append({"event_id": event_id, "updates": dict(updates)})
        return event_id

    def delete_event(self, event_id: str) -> bool:
        self.deleted.append(event_id)
        return True


def make_context(
    *,
    runtime: AgentRuntime,
    thread_id: str,
    gmail_client: Optional[FakeGmailClient] = None,
    gcal_client: Optional[FakeGCalClient] = None,
    user_id: str = "tester@example.com",
    agent_kind: str = "chat",
    mode: str = "semi_auto",
    shadow_mode: bool = False,
    source: str = "chat",
    rules: Optional[List[Dict[str, Any]]] = None,
    automation_settings: Optional[Dict[str, Any]] = None,
) -> InvocationContext:
    return InvocationContext(
        thread_id=thread_id,
        user_id=user_id,
        agent_kind=agent_kind,  # type: ignore[arg-type]
        mode=mode,  # type: ignore[arg-type]
        shadow_mode=shadow_mode,
        source=source,
        gmail_client=gmail_client,
        gcal_client=gcal_client,
        llm_client=runtime.llm_client,
        rules=rules or [],
        automation_settings=automation_settings or {},
    )


@pytest.fixture
def fake_gmail() -> FakeGmailClient:
    return FakeGmailClient()


@pytest.fixture
def fake_gcal() -> FakeGCalClient:
    return FakeGCalClient()


@pytest.fixture
def runtime_factory(tmp_path: Path):
    runtimes: List[AgentRuntime] = []

    def _make(
        *,
        llm_client: Optional[FakeLLMClient] = None,
        decision_engine: Any = None,
    ) -> AgentRuntime:
        root = tmp_path / f"runtime-{len(runtimes) + 1}"
        runtime = AgentRuntime(
            checkpoint_path=root / "checkpoints.sqlite",
            approvals_path=root / "approvals.json",
            work_items_path=root / "work_items.json",
            threads_path=root / "threads.json",
            timeline_path=root / "timeline.json",
            runs_path=root / "runs.json",
            memory_dir=root / "memory",
            llm_client=llm_client or FakeLLMClient(),
            decision_engine=decision_engine,
        )
        runtimes.append(runtime)
        return runtime

    yield _make

    for runtime in runtimes:
        runtime.close()
